### PR TITLE
Block matching

### PR DESCRIPTION
**Pull request by thewtex**
CC: @dzenanz 

Next steps are to add the tests.

### CODE REVIEW

**Comment by thewtex** [comment]
@dzenanz I will also merge int ITKStrain header files into this repository.

**Comment by thewtex** [comment]
CC: @sjh26

**Comment by dzenanz** [comment]
Is complex conjugate filter needed any more? In the place of invocation it seems to have been replaced by half-Hermitian (which already exists). It is just hard to go through all this code all at once :smile:

**Comment by thewtex** [comment]
> Is complex conjugate filter needed any more?

It is used by `itk::BlockMatchingNormalizedCrossCorrelationFFTMetricImageFilter`

**Pull request merged**
