### PR TITLE
ENH: Add example for generating power spectral density plot

### PR DESCRIPTION
**Pull request by tbirdso**
Adapting previous work from @dzenanz and @thewtex for example of power spectral density plots

### CODE REVIEW

**Comment by tbirdso** [comment]
@dzenanz Could you please confirm the sampling frequency for `MouseLiverRF.mha`? I arbitrarily guessed 30 MHz for now.

**Comment by dzenanz** [comment]
Either 40 or 60 MHz, @tomekcz probably knows.

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
Guessed sampling frequency @ 40 MHz for x-axis labels for now. Parameter can be updated in the future if needed.

**Comment by tomekcz** [comment]
Sorry for late response on this one, our Rf data is sampled at 60MHz.

**Comment by tbirdso** [comment]
No problem at all, thank you for the update @tomekcz. I'll amend the example accordingly.

**Pull request merged**
