### PR TITLE
Add wrapping and tests for PhasedArray3DSpecialCoordinatesImage

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Review by tbirdso — COMMENTED** [review]
Code looks good to me. @dzenanz can you confirm that Python tests pass locally on your system?

It looks like `itk::PhaseArray3DSpecialCoordinatesImage` is implemented in `ITK/Core/Common`, could you comment on the decision to add wrapping here in ITKUltrasound? Maybe the wrapping for `itk::PhaseArray3DSpecialCoordinatesImage` and general filters could be moved there and then the wrapping for ITKUltrasound spectral analysis filters could be kept here? Though I am not sure whether it is worth the effort or not.

**Comment by dzenanz** [comment]
All the tests pass locally, including the ones this PR adds.

I also though about adding wrapping to ITK/Core/Common, but:
1.  this class is somewhat specific to ultrasound
2. releasing a new version of `itk-ultrasound` is easier and faster than `itk`, and I need this to continue working on https://github.com/KitwareMedical/SlicerITKUltrasound/tree/pythonization.

Moving the wrapping to ITK core should be easy - just move the `.wrap` files there. We can discuss with @thewtex whether to do it for ITK 5.4 release.

**Comment by thewtex** [comment]
+1 for migrating this to ITK

**Comment by dzenanz** [comment]
Migrating to ITK via https://github.com/InsightSoftwareConsortium/ITK/pull/4101.

**Pull request merged**
