### PR TITLE
ENH: Register default curvilinear FFT factory overrides

### PR DESCRIPTION
**Pull request by tbirdso**
Leverages ITK Python factory updates introduced in 10320a6 to initialize
default backends to run FFT on
`itk::CurvilinearArraySpecialCoordinatesImage` objects. Includes
additional wrappings for image inputs.

Closes issue #172. Depends on ITK v5.3rc04.

### CODE REVIEW

**Comment by tbirdso** [comment]
Note that, like [https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend/pull/26](https://github.com/InsightSoftwareConsortium/ITKVkFFTBackend/pull/26), this PR relies on the `InitFactory` mechanism introduced in the ITK main branch which is anticipated to be included in a v5.3rc04 pre-release. Python CI will fail until ITK Python v5.3rc04 packages are available.

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
@dzenanz observed the following error in testing:

```
test 36
    Start 36: PythonSpectra1DAveragingImageFilterTest

36: Test command: C:\Dev\ITK-py\Wrapping\Generators\Python\itk\itkTestDriver.exe "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-py/Wrapping/Generators/Python" "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-py/Wrapping/Generators/Python/itk" "--add-before-libpath" "C:/Dev/ITK-py/Wrapping/Generators/Python/itk" "--compare" "C:/Dev/ITKUltrasound-2019/ExternalData/test/Input/spectra_pixel_image.mha" "C:/Dev/ITKUltrasound-2019/Testing/Temporary/PythonSpectra1DAveragingImageFilterTest.mha" "C:/Program Files/Python37/python.exe" "PythonSpectra1DAveragingImageFilterTest.py" "-o" "C:/Dev/ITKUltrasound-2019/Testing/Temporary/PythonSpectra1DAveragingImageFilterTest.mha" "-i" "C:/Dev/ITKUltrasound-2019/ExternalData/test/Input/spectra_pixel_image.mha" "-i" "C:/Dev/ITKUltrasound-2019/ExternalData/test/Input/spectra_pixel_image.mha" "-i" "C:/Dev/ITKUltrasound-2019/ExternalData/test/Input/spectra_pixel_image.mha"
36: Test timeout computed to be: 1500
36: Traceback (most recent call last):
36:   File "PythonSpectra1DAveragingImageFilterTest.py", line 20, in <module>
36:     import itk
36:   File "C:\Dev\ITK-py\Wrapping\Generators\Python\itk\__init__.py", line 159, in <module>
36:     _initialize_module()
36:   File "C:\Dev\ITK-py\Wrapping\Generators\Python\itk\__init__.py", line 53, in _initialize_module
36:     from .support.base import ITKModuleInfo, ITKTemplateFeatures
36:   File "C:\Dev\ITK-py\Wrapping\Generators\Python\itk\support\base.py", line 463, in <module>
36:     _initialize(itk_base_global_module_data)
36:   File "C:\Dev\ITK-py\Wrapping\Generators\Python\itk\support\base.py", line 458, in _initialize
36:     l_module_data[module] = ITKModuleInfo(conf, snake_conf)
36:   File "C:\Dev\ITK-py\Wrapping\Generators\Python\itk\support\base.py", line 398, in __init__
36:     content_info = importlib.import_module(f"itk.Configuration.{module_name}")
36:   File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
36:     return _bootstrap._gcd_import(name[level:], package, level)
36:   File "C:\Dev\ITK-py\Wrapping\Generators\Python\itk\Configuration\UltrasoundConfig.py", line 252
36:     ('ComplexToComplex1DFFTImageFilter', 'itk::ComplexToComplex1DFFTImageFilter', 'itkComplexToComplex1DFFTImageFilterCASCICF2CASCICF2', False, 'itk::CurvilinearArraySpecialCoordinatesImage< std::complex< float >, 2 >,
36:                                                                                                                                                                                                                          ^
36: SyntaxError: EOL while scanning string literal
36: itkTestDriver: Process exited with return value: 1
```

I also observed this error in development, thought it was fixed but was incorrect. The root issue lies in the new wrapping for `itk::ComplexToComplex1DFFTImageFilter` with `itk::CurvilinearArraySpecialCoordinatesImage` inputs. This creates a very long SWIG wrapping entry in `UltrasoundConfig.py`. Apparently the file generator attempts to wrap this long line onto to lines, but the parser loading in the module at runtime cannot parse entries wrapped across lines, so the parse fails.

A few potential paths of investigation to resolve:
- A short-term fix is to simply remove the wrapping if possible. I'm not sure if this is feasible as I believe this wrapping was required for `BModeImageFilter` wrappings to succeed, but I might be wrong.
- A long-term fix would be to either 1) stop the line break from happening or 2) configure the parser to recognize and accept wrapped lines. This investigation would happen in ITK proper.
- A potential workaround would be to 1) rename one of the classes to have a shorter name (not desirable) or 2) create aliases in the itk namespace to allow wrappings to succeed with shorter names (slightly better, but prone to causing confusion)

**Comment by thewtex** [comment]
> A long-term fix would be to either 1) stop the line break from happening or 2) configure the parser to recognize and accept wrapped lines. This investigation would happen in ITK proper.

+1

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
Squashed changes

**Pull request merged**
