### PR TITLE
GitHub actions

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #106. Closes #120.

### CODE REVIEW

**Comment by dzenanz** [comment]
This should work now, but for some reason the build gets interrupted. E.g [run_id 1305250375](https://github.com/KitwareMedical/ITKUltrasound/pull/121/checks?check_run_id=1305250375):
```text
[1268/2159] Building CXX object Modules\ThirdParty\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\CMakeFiles\gdcmMSFF.dir\gdcmImageApplyLookupTable.cxx.obj
ninja: build stopped: interrupted by user.
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.7.9\x64\Scripts\ninja.exe\__main__.py", line 7, in <module>
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\ninja\__init__.py", line 50, in ninja
    raise SystemExit(_program('ninja', sys.argv[1:]))
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\site-packages\ninja\__init__.py", line 46, in _program
    return subprocess.call([os.path.join(BIN_DIR, name)] + args)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\subprocess.py", line 341, in call
    return p.wait(timeout=timeout)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\subprocess.py", line 1259, in _wait
    timeout_millis)
KeyboardInterrupt
Terminate batch job (Y/N)? 
Error: The operation was canceled.
```

**Comment by thewtex** [comment]
> This should work now, but for some reason the build gets interrupted. 

This is for the ITK build -- is it related to the ITK version? Could you try different versions?

**Comment by dzenanz** [comment]
I force-pushed a change to `v5.1.1` tag.

**Comment by thewtex** [comment]
> I just force-pushed a change to v5.1.1 tag.

@dzenanz thanks!

Same failure.

>   File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\subprocess.py", line 1019, in wait
    return self._wait(timeout=timeout)
  File "c:\hostedtoolcache\windows\python\3.7.9\x64\lib\subprocess.py", line 1259, in _wait
    timeout_millis)

@jcfr This error is sparking a memory... if I recall correctly, there is unexpected timeouts when `ninja.exe` is called as a Python subprocess. I do not recall how we addressed this or if we did. Looking into *ninja-python-distributions*, I cannot find any open or closed issues.

@dzenanz in the CI configuration, there is a different build common used for Windows -- please use the same pattern for the install job, and do non `pip install ninja` -- we will use the version that comes vendored with Visual Studio 2019.

**Comment by jcfr** [comment]
> I do not recall how we addressed this or if we did. Looking into ninja-python-distributions, I cannot find any open or closed issues.

The issue was discussed here: https://github.com/InsightSoftwareConsortium/ITKExamples/pull/180#issuecomment-677762808

In a nutshell, you can get the directory of the ninja executable doing something like this:

```
python -c "import ninja; print(ninja.BIN_DIR)"
/home/jcfr/.virtualenvs/system-py35/lib/python3.5/site-packages/ninja/data/bin
```
 and then prepend the value to `PATH` so that it is discovered.

**Comment by dzenanz** [comment]
I have gotten this down to are two problems, ninja timeout on MacOS and wheel building for dependent remote modules. I will try JC's suggestion for timeout. Matt and I need to discuss the best way to proceed regarding wheels. Postponing both for next week.

**Review by thewtex — APPROVED** [review]
I think we could merge this and continue in follow-up commits.

**Comment by dzenanz** [comment]
Should we [disable CircleCI](https://app.circleci.com/settings/project/github/KitwareMedical/ITKUltrasound) now? Are Azure pipelines enabled?

**Pull request merged**
