### PR TITLE
ENH: Add wrapping files for forward and inverse 1D FFT filter

### PR DESCRIPTION
**Pull request by tbirdso**

### CODE REVIEW

**Comment by thewtex** [comment]
Thanks, @tbirdso !

First, please bump the dependencies:

https://github.com/KitwareMedical/ITKUltrasound/blob/master/.github/workflows/build-test-package.yml#L6-L9

to be based on `v5.2.0.post2`, then bump ITKUltrasound, then rebase this so we stay green. 📗

**Review by dzenanz — APPROVED** [review]
Code looks good, it would be good if CI was fixed so it has a chance to possibly uncover a problem 😄

**Comment by tbirdso** [comment]
@thewtex @dzenanz I've submitted PRs to bump the CI ITK version in each external module dependency, I don't have permissions to add reviewers but I tried to @ you in each PR.

Modules are ITKBSplineGradient, ITKHigherOrderAccurateGradient, ITKSplitComponents, ITKStrain.

**Comment by tbirdso** [comment]
Also see #143 .

**Comment by thewtex** [comment]
> ITKBSplineGradient, ITKHigherOrderAccurateGradient, ITKSplitComponents, ITKStrain.

These are now all updated.

**Comment by tbirdso** [comment]
Rebased on #144 to get green CI.

**Review by thewtex — APPROVED** [review]
🚀  🐍 

@Leengit eventually we will want the accelerated versions of these classes.

**Pull request merged**
