### PR TITLE
BUG: Update CurvilinearArray baseline

### PR DESCRIPTION
**Pull request by thewtex**
The baseline image had an extra third dimension which was confusing the
metadata check.

### CODE REVIEW

**Comment by thewtex** [comment]
@fbudin69500 FYI, related to the new image information checks.

**Comment by fbudin69500** [comment]
@thewtex Can you be more explicit?

**Comment by thewtex** [comment]
As experienced in this commit, the new image metadata checks with also throw an error when a test image vs a baseline have different dimensions even though the spacing, etc. are the same. Just something to aware of in case other folks need help with it.

**Comment by fbudin69500** [comment]
Indeed. I think the tolerance used for spacing and size is the same in the
itkImageToImageFilter, so I don't think it is possible to deactivate one
check without deactivating the other one, without modifying the filter.

**Pull request merged**
