### PR TITLE
BUG: Fix a copy-paste bug in Python unit test

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
@tom do we run Python unit tests in the CI?

**Comment by tbirdso** [comment]
@dzenanz We do not run Python test in CI, primarily due to issues with building and scheduling tests with CMake in our Python workflow. Jupyter notebooks can be run as part of CI, we could look at adding support for pytest or other Python-specific test frameworks in the future.

**Comment by dzenanz** [comment]
I think that tests were passing locally because the file existed in the temporary directory from some previous runs. Starting from a clean build I ran into this issue.

**Review by tbirdso — COMMENTED** [review]
Looks good 👍 Thanks

**Pull request merged**
